language: node_js
node_js:
  - '4.3'
  - '5.11'
  - '6.2'
matrix:
#  allow_failures:
#    - node_js: "4.3"
  fast_finish: true
before_install: npm install -g grunt-cli
install:
  - npm install
  - npm install -g npm
notifications:
    email:
        on_failure: always
